apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: inventory-db-credentials
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: inventory-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # URL encoding happens here: password | urlquery
        DATABASE_URL: >-
          postgresql://{{ .username }}:{{ .password | urlquery }}@{{ .host }}:{{ .port }}/jimag_inventory?schema=public

  data:
    - secretKey: username
      remoteRef:
        key: /jimag/dev/inventory/db
        property: username
    - secretKey: password
      remoteRef:
        key: /jimag/dev/inventory/db
        property: password
    - secretKey: host
      remoteRef:
        key: /jimag/dev/inventory/db
        property: host
    - secretKey: port
      remoteRef:
        key: /jimag/dev/inventory/db
        property: port