apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - db-seed-job.yaml
  - external-secret-db.yaml
patches:
  - path: patch-env.yaml
images:
  - name: 329551316753.dkr.ecr.us-east-1.amazonaws.com/jimag-dev-inventory-svc
    newTag: dev-3175f11c851526a3388876f841444d42e23706df
# Patches for dev-specific overrides (optional for now)
# patches:
#   - path: patch-env.yaml
