apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - configmap.yaml
  - db-seed-job.yaml
  - external-secret-db.yaml
patches:
  - path: patch-env.yaml
images:
  - name: 329551316753.dkr.ecr.us-east-1.amazonaws.com/jimag-dev-inventory-svc
    newTag: dev-de844de4b7ff7c103504bb67d59e4fe0e7521b3a
# Patches for dev-specific overrides (optional for now)
# patches:
#   - path: patch-env.yaml
