apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-svc
spec:
  template:
    spec:
      containers:
        - name: inventory-svc
          env:
            - name: NODE_ENV
              value: "development"


