apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-svc
spec:
  template:
    spec:
      containers:
        - name: inventory-svc
          image: 329551316753.dkr.ecr.us-east-1.amazonaws.com/jimag-dev-inventory-svc:dev-fcb15c85e0aefc30bc55ed824a8a5e749cc465fe
          env:
            - name: NODE_ENV
              value: "development"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: inventory-db-credentials
                  key: DATABASE_URL  
