apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-svc
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      serviceAccountName: inventory-svc

      containers:
        - name: inventory-svc
          image: 329551316753.dkr.ecr.us-east-1.amazonaws.com/jimag-dev-inventory-svc:dev-PLACEHOLDER

          envFrom:
            - configMapRef:
                name: inventory-svc-config

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: inventory-db-credentials
                  key: DATABASE_URL

          ports:
            - containerPort: 3001
              name: http

          startupProbe:
            httpGet:
              path: /api/healthz
              port: 3001
            periodSeconds: 5
            failureThreshold: 24

          readinessProbe:
            httpGet:
              path: /api/readyz
              port: 3001
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3001
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi