apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-svc
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    eks.amazonaws.com/role-arn: arn:aws:iam::329551316753:role/jimag-dev-inventory-s3-irsa