apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 329551316753.dkr.ecr.us-east-1.amazonaws.com/jimag-dev-frontend:dev-placeholder
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            # Example: how frontend talks to backend INSIDE the cluster
            - name: NEXT_PUBLIC_API_BASE
              value: "http://inventory-svc.dev.svc.cluster.local/api"  # for example, depending on namespace

          startupProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            periodSeconds: 5
            failureThreshold: 24

          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
