apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  NEXT_PUBLIC_API_BASE: "http://inventory-svc.dev.svc.cluster.local/api"
  PUBLIC_IMAGE_BASE: "https://jimag-dev-car-images.s3.us-east-1.amazonaws.com"
  NEXT_PUBLIC_IMAGE_BASE: "https://jimag-dev-car-images.s3.us-east-1.amazonaws.com"
  NEXT_PUBLIC_SITE_NAME: "Jimag Autos Marketplace"
  NODE_ENV: "development"
  NEXT_PUBLIC_S3_PUBLIC_BASE: "https://jimag-dev-car-images.s3.us-east-1.amazonaws.com"