apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - configmap.yaml
  - ingress.yaml

patches:
  - path: patch-env.yaml
images:
  - name: 329551316753.dkr.ecr.us-east-1.amazonaws.com/jimag-dev-car-website-frontend
    newTag: dev-be7cdf855e4c44f27b12f4971a48ef93f76dc27f
