apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - configmap.yaml

patches:
  - path: patch-env.yaml

images:
  - name: 329551316753.dkr.ecr.us-east-1.amazonaws.com/jimag-dev-car-website-frontend
    newTag: dev-fcb15c85e0aefc30bc55ed824a8a5e749cc465fe