apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-frontend
spec:
  template:
    spec:
      containers:
        - name: car-frontend
          env:
            - name: NODE_ENV
              value: "development"


